### ISSUE TITLE
How about the gpu performance as compared to tensorflow

### ISSUE THREAD

**Issue by twmht** [lhCheung1991/deeplearning-model-convertor#1]
Hi,

Did you compare the gpu performance as compared to tensorflow?

**Comment by lhCheung1991** [comment]
@twmht 
Do you mean the performance comparison between TF and Caffe2 in training stage?

**Comment by twmht** [comment]
@lhCheung1991 

I meant the inference fps, not training performance.

I can only see the performance of cpu in the blog.

**Comment by lhCheung1991** [comment]
@twmht 
No... I just want to deploy the model to Caffe2 on ARM CPU.

**Comment by twmht** [comment]
ok.

thank you
